services:
  dcoya-blog:
    build: ./server/
    depends_on:
      - dcoya_db
    ports:
      - '8000:8000'

  dcoya_db:
    build: ./sql/
    restart: always
    environment:
      MYSQL_DATABASE: 'root'
      MYSQL_ROOT_PASSWORD: '986532'
    ports:
      - '3307:3307'

