services:
  dcoya-blog:
    build: ./server/
    command: sh -c "sleep 10s ; python ./server.py"
    depends_on:
      - dcoya_db
    ports:
      - '8000:8000'

  dcoya_db:
    build: ./sql/
    restart: always
    environment:
      MYSQL_DATABASE: dcoya
      MYSQL_ROOT_PASSWORD: '986532'
 
    ports:
      - '6603:3306'

